"""
MiniLM Model Loader — dual-mode
=================================
Loads sentence-transformers/all-MiniLM-L6-v2.

Primary:  SentenceTransformer API (>=2.6.0) — handles pooling + L2 norm internally
Fallback: AutoTokenizer + AutoModel with manual mean-pooling + L2 norm
          (same mathematical result, uses the already-installed transformers library)

Either way the output is:
  - 384-dimensional float vectors
  - L2-normalised (cosine similarity = dot product)
  - Generated by the same model for both query and product text
"""

import logging
from typing import List, Optional

import torch
import torch.nn.functional as F
import numpy as np
from transformers import AutoTokenizer, AutoModel

from config import Config

logger = logging.getLogger(__name__)


def _mean_pool_normalize(model_output, attention_mask) -> torch.Tensor:
    """
    Mean-pool the last hidden states over non-padding tokens, then L2-normalise.
    This is the standard pooling strategy for all-MiniLM-L6-v2.
    """
    token_embeddings = model_output.last_hidden_state          # (B, T, D)
    mask = attention_mask.unsqueeze(-1).float()                # (B, T, 1)
    summed  = (token_embeddings * mask).sum(dim=1)             # (B, D)
    counts  = mask.sum(dim=1).clamp(min=1e-9)                  # (B, 1)
    pooled  = summed / counts                                   # (B, D)
    return F.normalize(pooled, p=2, dim=1)                     # L2-norm


class MiniLMLoader:
    """
    Singleton loader for all-MiniLM-L6-v2.
    Uses SentenceTransformer when available; falls back to raw transformers.
    """

    _instance: Optional['MiniLMLoader'] = None
    _tokenizer = None
    _model     = None
    _st_model  = None   # SentenceTransformer instance if available

    def __new__(cls) -> 'MiniLMLoader':
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    def __init__(self):
        if self._tokenizer is None and self._st_model is None:
            self._load_model()

    def _load_model(self) -> None:
        """Try SentenceTransformer first; fall back to raw transformers."""
        try:
            from sentence_transformers import SentenceTransformer
            logger.info(f"Loading via SentenceTransformer: {Config.MODEL_NAME}")
            self._st_model = SentenceTransformer(Config.MODEL_NAME)
            dim = self._st_model.get_sentence_embedding_dimension()
            logger.info(f"Loaded model       : {Config.MODEL_NAME}")
            logger.info(f"Embedding dimension: {dim}")
            if dim != 384:
                logger.warning(f"Expected 384-dim but got {dim} — check MODEL_NAME in .env")
        except Exception as st_err:
            logger.warning(f"SentenceTransformer load failed ({st_err}); using raw transformers fallback")
            try:
                logger.info(f"Loading via AutoModel: {Config.MODEL_NAME}")
                self._tokenizer = AutoTokenizer.from_pretrained(Config.MODEL_NAME)
                self._model     = AutoModel.from_pretrained(Config.MODEL_NAME)
                self._model.eval()
                logger.info(f"Loaded model       : {Config.MODEL_NAME}")
                logger.info(f"Embedding dimension: {Config.EMBEDDING_DIM} (MiniLM)")
            except Exception as e:
                logger.error(f"Failed to load model with both methods: {e}")
                raise

    # ------------------------------------------------------------------ #
    #  Public interface                                                    #
    # ------------------------------------------------------------------ #

    def embed(self, texts: List[str]) -> List[List[float]]:
        """Encode a list of texts → list of 384-dim L2-normalised float lists."""
        if not texts:
            return []

        if self._st_model is not None:
            # SentenceTransformer path (normalise_embeddings=True → L2 norm)
            vecs = self._st_model.encode(
                texts,
                normalize_embeddings=True,
                batch_size=32,
                show_progress_bar=False,
            )
            return vecs.tolist()
        else:
            # Raw transformers path
            return self._raw_embed(texts)

    def embed_one(self, text: str) -> List[float]:
        """Encode a single text."""
        return self.embed([text])[0]

    # ------------------------------------------------------------------ #
    #  Raw transformers fallback                                           #
    # ------------------------------------------------------------------ #

    def _raw_embed(self, texts: List[str]) -> List[List[float]]:
        """
        Manual mean-pool + L2 norm with AutoModel.
        Processes in mini-batches of 32 to avoid OOM on large candidate sets.
        """
        results = []
        batch_size = 32

        for start in range(0, len(texts), batch_size):
            batch = texts[start : start + batch_size]
            inputs = self._tokenizer(
                batch,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=256,
            )
            with torch.no_grad():
                outputs = self._model(**inputs)
            normed = _mean_pool_normalize(outputs, inputs["attention_mask"])
            results.extend(normed.numpy().tolist())

        return results
